#!/bin/bash
#**********************************************************************
#***                                                                ***
#*** Script:  apl360_client                                         ***
#***                                                                ***
#*** Purpose: Start a PuTTY telnet session for use with             ***
#***          APL\360 on Linux.                                     ***
#***                                                                ***
#*** Updated: 2013/03/23                                            ***
#***                                                                ***
#**********************************************************************
PuTTY-0.62_for_Hercules/linux/putty -load APL360 &
